### ISSUE TITLE
Mouse cursor jumps around the screen.

### ISSUE THREAD

**Issue by masakk1** [mariotaku/moonlight-tv#394]
### Moonlight Version

v1.6.11 pre-release

### Device Type

webOS TV

### Device Model

LG 50UM7600PLB

### Device OS

webOS 4.10.0

### Host OS

Linux

### Host Software

Sunshine

### Host Setup

1. AMD Ryzen 5 5600
2. NVIDIA Geforce RTX 3060
3. 16 GB RAM
4. Fedora Linux 39 - particularly Nobara

### Bug Description

The cursor on the screen jumps from where I'm pointing and the middle. It's the TV's cursor that is jumping around, not the one on the PC, although that one is also affected by this.

The cursor keeps jumping even after opening the home screen. It only stops after closing moonlight.

https://github.com/mariotaku/moonlight-tv/assets/105455722/7e3218e6-82ab-43fc-bf62-0ea44e215c66

### Reproduction Steps

1. Open moonlight
2. Cursor proceeds to freak out.

### Expected Behavior

The cursor shouldn't jump around.

**Comment by mariotaku** [comment]
Hi, does the cursor work now?

**Comment by mariotaku** [comment]
Closing as the cursor issue should be properly addressed in the latest releases.

**Comment by masakk1** [comment]
I can't currently test that, and I'll probably forget again, but I definitely tried again and the issue still persisted.

Again, I can't confirm, just letting you know. If I use my TV at some point again I'll try to remember to test again.

**Comment by mariotaku** [comment]
Just tried again on UM7600 with v1.6.29. It worked well. Make sure you have the latest Moonlight version, the new version not only fixed the problem but also improved mouse refresh rate.
