### ISSUE TITLE
Moonlight can't save settings on webOS (Permission issue)

### ISSUE THREAD

**Issue by Isackti** [mariotaku/moonlight-tv#505]
### Moonlight Version

1.6.29

### Device Type

webOS TV

### Device Model

LG 43UJ6300-SA

### Device OS

webOS 3.9.0

### Host OS

Windows

### Host Software

Sunshine

### Bug Description

Can't save settings. Can't find a writable directory to save settings. Settings and pairing information will be lost when the TV is turned off.

### Expected Behavior

![Image](https://github.com/user-attachments/assets/882219ca-668b-4cbf-a4f4-1fea1b981f84)

**Comment by mariotaku** [comment]
Hello, did you try turning the TV off? (Also by unplug to make sure)

**Comment by Isackti** [comment]
> Hola, ¿intentaste apagar el televisor? (También desenchufando para asegurarse)

Yes, I have tried turning the TV off, including unplugging it completely, but the issue persists. Every time I restart the TV, the settings and pairing information are lost, and I get the same error message.

**Comment by Zigngit** [comment]
Same issue here, and I am using webos 2.2.0
I am using webos dev manager, can you tell me how and which dir to verify the permission.
Or have I to root this tv?

**Comment by mylo599** [comment]
Hey Everyone!

I got this solved by opening the developer app on the TV and turning on key server - somehow it was turned off for me.

I hope this could help some of you.

**Comment by goovc22** [comment]
Has anyone managed to fix this issue? For me, the server key turns off every time, and even when it's on, I still get this error.  I have lg oled65c7

**Comment by mariotaku** [comment]
@goovc22 They key server has nothing to do with this issue. Usually, after a clean reboot, the permission of the app should be fixed if you have webOS 3+.

**Comment by pilos011** [comment]
@Isackti 

cd /media/developer/apps/usr/palm/applications/

root@LGSmartTV:/media/developer/apps/usr/palm/applications# ls -al
total 20
drwxrwxr-x    5 root     root          4096 Aug 17 16:54 .
drwxrwxr-x    5 root     root          4096 Aug 11 23:04 ..
drwxrwxrwx    8 root     root          4096 Aug 17 16:38 com.limelight.webos
drwxrwxrwx    4 root     root          4096 Aug 17 10:21 org.webosbrew.hbchannel
drwxrwxrwx    3 root     root          4096 Aug 17 12:57 youtube.leanback.v4


chmod 777 com.limelight.webos


Just give all user write permissions (777) to limelight folder. Simple!

**Comment by Frens98** [comment]
I am also having this issue, on 55UJ630V-ZA, with latest firmware 06.10.75, WebOS 3.9. Not rooted (cannot even root latest firmware)
Already tried reinstalling Moonlight by LG WebOS Manager as wel as Homebrew Channel on TV itself.

**Comment by Braekpo1nt** [comment]
I have webOS 3.9.0 and I'm still getting this issue. Tried restarting TV, unplugging and plugging back in, uninstalling and reinstalling Moonlight app, and still the issue persists. 
```
ls -la /media/developer/apps/usr/palm/applications/com.limelight.webos
<
total 76
drwxrwxr-x    6 root     root          4096 Mar 12 15:52 .
drwxrwxr-x    3 root     root          4096 Mar 12 15:52 ..
-rw-r--r--    1 root     root           452 Mar 12 15:52 appinfo.json
drwxrwxr-x    2 root     root          4096 Mar 12 15:52 assets
drwxrwxr-x    2 root     root          4096 Mar 12 15:52 bin
-rw-r--r--    1 root     root          3257 Oct 18 07:56 icon.png
-rw-r--r--    1 root     root          5762 Oct 18 07:56 icon_large.png
drwxrwxr-x    3 root     root          4096 Mar 12 15:52 lib
drwxrwxr-x   13 root     root          4096 Mar 12 15:52 resources
-rw-r--r--    1 root     root         36192 Oct 18 07:56 splash.png
```
It seems the install fails to create a writable data directory. I can still use Moonlight, but settings are not saved.

**Comment by SpenceGray** [comment]
I had this issue. What worked for me:
On your LG TV goto Settings > General > About This TV > User Agreements
Uncheck 'Terms of Use' and 'Privacy Policy'
Click Agree
A 'Terms of Service Have Changed' pop-up will appear, choose Yes
TV will now restart itself and apply changes

Moonlight should now no longer have the permissions settings pop-up come up. Go back and recheck the ToS/Privacy settings and let the TV reset and re-apply, Moonlight will still work as expected.

Cheers
